In [1]:
# 模块导入
import torch
import torchvision
import numpy as np
import torch.nn as nn
import torchvision.transforms as transform

In [ ]:
# Create tensors

x = torch.tensor(1,requires_grad=True)
w = torch.tensor(2,requires_grad=True)
b = torch.tensor(3,requires_grad=True)

In [ ]:
# Bulid a computational graph
y = w * x + b

In [ ]:
# COmpute gradients
y.backward()

In [12]:
# Print out the gradients
print(x.grad)
print(w.grad)
print(b.grad)


None
None
None


In [2]:
#############################
# 2. Basic autograd example 2
#############################

# Create tensors of shape (10, 3)  and (10, 2)
x = torch.randn(10, 3)
y = torch.randn(10,2)
print('x:', x)
print('y:', y)

x: tensor([[ 0.2778,  0.1726, -0.0325],
        [ 1.0424, -0.4064, -0.9440],
        [ 0.9072,  1.5678, -0.2646],
        [ 0.3705,  0.5586,  0.5936],
        [ 2.0488, -0.2947, -1.5168],
        [ 1.4207,  0.3935, -1.3024],
        [-0.9553,  0.4497,  1.1447],
        [-0.9580, -0.4197,  0.9363],
        [-0.6950,  0.0850, -3.1610],
        [-0.5231,  0.3278, -0.5197]])
y: tensor([[ 0.9649, -0.9799],
        [ 0.1179,  0.2352],
        [-0.0608,  0.5355],
        [-0.0350, -0.1841],
        [ 0.6220,  1.0590],
        [-1.5755, -0.1924],
        [-1.0953,  0.4419],
        [ 1.8364,  1.2967],
        [ 0.9418,  0.9669],
        [ 0.7640, -0.0749]])


In [3]:
# BUild a fully connected layer

linear = nn.Linear(3,2)
print(linear)

Linear(in_features=3, out_features=2, bias=True)


In [4]:
print('w:', linear.weight)
print('b:', linear.bias)

w: Parameter containing:
tensor([[ 0.4739, -0.1928, -0.5118],
        [ 0.2435,  0.4443,  0.1254]], requires_grad=True)
b: Parameter containing:
tensor([-0.2551,  0.4467], requires_grad=True)


In [6]:
# Build loss function and optimizer

criterion = nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(),lr=0.01)

In [7]:
# Forward pass
pred = linear(x)
# Compute loss
loss = criterion(pred, y)
print('loss:', loss.item())

loss: 1.3687126636505127


In [8]:
# Print out the gradients

print('dL/dw:',linear.weight.grad)
print('dL/db:', linear.bias.grad)


dL/dw: None
dL/db: None


In [9]:
# 1-step gradient descent
optimizer.step()


In [10]:
pred = linear(x)
loss = criterion(pred,y)
print('loss after 1 step optimization:', loss.item())

loss after 1 step optimization: 1.3687126636505127


In [11]:
#############################
# 3. Loading data from numpy
#############################

# Create a numpy array
x = np.array([[1,2],[3,4]])
# Convert the numpy aray to a torh tensor
y = torch.from_numpy(x)
# Convert the torch tensor to a numpy array
z = y.numpy()

In [29]:
#############################
# 4.Input pipline
#############################

In [12]:
# Download and construct CIFaR-10 dataset

train_dataset = torchvision.datasets.CIFAR10(root='../../data/',
                                            train = True,
                                            transform=transform.ToTensor(),
                                            download= True)

In [14]:
# Fetch one data pair (read data from disk)

image, label = train_dataset[0]

In [16]:
print(image)

tensor([[[0.2314, 0.1686, 0.1961,  ..., 0.6196, 0.5961, 0.5804],
         [0.0627, 0.0000, 0.0706,  ..., 0.4824, 0.4667, 0.4784],
         [0.0980, 0.0627, 0.1922,  ..., 0.4627, 0.4706, 0.4275],
         ...,
         [0.8157, 0.7882, 0.7765,  ..., 0.6275, 0.2196, 0.2078],
         [0.7059, 0.6784, 0.7294,  ..., 0.7216, 0.3804, 0.3255],
         [0.6941, 0.6588, 0.7020,  ..., 0.8471, 0.5922, 0.4824]],

        [[0.2431, 0.1804, 0.1882,  ..., 0.5176, 0.4902, 0.4863],
         [0.0784, 0.0000, 0.0314,  ..., 0.3451, 0.3255, 0.3412],
         [0.0941, 0.0275, 0.1059,  ..., 0.3294, 0.3294, 0.2863],
         ...,
         [0.6667, 0.6000, 0.6314,  ..., 0.5216, 0.1216, 0.1333],
         [0.5451, 0.4824, 0.5647,  ..., 0.5804, 0.2431, 0.2078],
         [0.5647, 0.5059, 0.5569,  ..., 0.7216, 0.4627, 0.3608]],

        [[0.2471, 0.1765, 0.1686,  ..., 0.4235, 0.4000, 0.4039],
         [0.0784, 0.0000, 0.0000,  ..., 0.2157, 0.1961, 0.2235],
         [0.0824, 0.0000, 0.0314,  ..., 0.1961, 0.1961, 0.

In [19]:
# Data loader (this provides queues and threads threads in a very simple way).
train_loader = torch.utils.data.DataLoader(dataset=train_dataset,
                                          batch_size=64,
                                          shuffle=True)

In [23]:
# When iteration starts, queue and thread start to load data fro files.

data_iter = iter(train_loader)

# Mini-batchs images and labels
images, labels = data_iter.next()

# Actual usage of the data loader is ad below 

for images, labels in train_loader:
    # Training code should be written here
    pass

In [24]:
# You should your build your custom dataset as below.

class CustomDataset(torch.utils.data.Dataset):
    def __init__(self):
        
        def __getitem__(self, index):
            pass
        
        def __len__(self):
            return 0
        

In [25]:
# you can then use the prebuilt data loader
custom_dataset = CustomDataset()
train_loader = torch.utils.data.DataLoader(dataset=custom_dataset,
                                          batch_size=64,
                                          shuffle=True)

In [26]:
# Download and load the pretrained ResNet-18
resnet = torchvision.models.resnet18(pretrained=True)


# If you want to finetune only the top layer of the model, set as below .

for param in resnet.parameters():
    param.requires_grad = False
    


Downloading: "https://download.pytorch.org/models/resnet18-5c106cde.pth" to /home/xm/.torch/models/resnet18-5c106cde.pth
100.0%


In [27]:
resnet.fc = nn.Linear(resnet.fc.in_features, 100) # 100 is an example

In [28]:
# Forward pass

images = torch.randn(64,3,224,224)
outputs = resnet(images)

print(outputs.size())



torch.Size([64, 100])


In [30]:
# save and load the model

torch.save(resnet, 'model.ckpt')
model = torch.load('model.ckpt')

# Save and load only the model paramters (recommended)

torch.save(resnet.state_dict(), 'params.ckpt')
resnet.load_state_dict(torch.load('params.ckpt'))